config/routes.rb
Rails.application.routes.draw do
  resources :jobs, path: "/" do
    patch "stage", on: :member
    patch "submit", on: :member
    patch "stop", on: :member
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  # Required parameters
  enum status: [:unsubmitted, :submitted, :completed]
  store :job_params, coder: JSON

  # Hooks
  after_initialize :set_defaults

  # Set default values
  def set_defaults
    self.cluster_id ||= "owens"
  end

  # Custom parameters
  store_accessor :job_params, :project
  store_accessor :job_params, :param1
  store_accessor :job_params, :param2
  store_accessor :job_params, :notes

  # Validations
  validates :project, :param1, :param2, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all.map { |job| JobPresenter.new(job) }
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = JobPresenter.new Job.find(params[:id])
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /jobs/1/stage
  # PATCH /jobs/1/stage.json
  def stage
    @job = Job.find(params[:id])

    result = StageTemplate.new(@job).call
    respond_to do |format|
      if result.success?
        format.html { redirect_to jobs_url, notice: "Job was successfully staged." }
        format.json { head :no_content }
      else
        format.html { redirect_to jobs_url, alert: result.error }
        format.json { render json: { error: result.error }, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /jobs/1/submit
  # PATCH /jobs/1/submit.json
  def submit
    @job = Job.find(params[:id])

    result = SubmitJob.new(@job).call
    respond_to do |format|
      if result.success?
        format.html { redirect_to jobs_url, notice: "Job was successfully submitted." }
        format.json { head :no_content }
      else
        format.html { redirect_to jobs_url, alert: result.error }
        format.json { render json: { error: result.error }, status: :unprocessable_entity }
      end
    end
  end

  # PATCH /jobs/1/stop
  # PATCH /jobs/1/stop.json
  def stop
    @job = Job.find(params[:id])

    result = StopJob.new(@job).call
    respond_to do |format|
      if result.success?
        format.html { redirect_to jobs_url, notice: "Job was successfully stopped." }
        format.json { head :no_content }
      else
        format.html { redirect_to jobs_url, alert: result.error }
        format.json { render json: { error: result.error }, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])

    result = DestroyJob.new(@job).call
    respond_to do |format|
      if result.success?
        format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
        format.json { head :no_content }
      else
        format.html { redirect_to jobs_url, alert: result.error }
        format.json { render json: { error: result.error }, status: :unprocessable_entity }
      end
    end
  end

  private
    def job_params
      params.require(:job).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when "notice"
      "alert-success"
    when "alert"
      "alert-danger"
    end
  end
end

app/views/jobs/_form.html.erb
<div class="row justify-content-start">
  <div class="col-6">
    <%= form_for(@job) do |f| %>
      <div class="form-group">
        <%= f.label :project %><br>
        <%= f.text_field :project, class: "form-control", "aria-describedby" => "projectHelpBlock" %>
        <small id="projectHelpBlock" class="form-text text-muted">
          Project to be charged against.
        </small>
      </div>
      <div class="form-group">
        <%= f.label :param1 %><br>
        <%= f.number_field :param1, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :param2 %><br>
        <%= f.text_field :param2, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :notes %><br>
        <%= f.text_area :notes, class: "form-control" %>
      </div>
      <%= button_tag icon("fas", "save", "Save"), class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
</div>

app/views/jobs/edit.html.erb
<h1 class="display-4 pb-2 my-2 border-bottom">
  Edit Batch Job
</h1>

<%= render 'form' %>

app/views/jobs/index.html.erb
<h1 class="display-4 my-2">
  My Batch Jobs
  <span class="float-right">
    <%=
      link_to(
        icon("fas", "plus", "New Batch Job"),
        new_job_path,
        class: "btn btn-secondary"
      )
    %>
  </span>
</h1>

<table class="table">
  <caption>
    Last updated <%= DateTime.now.strftime("%b %e %I:%M:%S%p %Z") %>
  </caption>

  <thead class="thead-light">
    <tr>
      <th scope="col">Project</th>
      <th scope="col">Param1</th>
      <th scope="col">Param2</th>
      <th scope="col">Notes</th>
      <th scope="col">Status</th>
      <th colspan="7" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td scope="row"><%= job.project %></td>
        <td scope="row"><%= job.param1 %></td>
        <td scope="row"><%= job.param2 %></td>
        <td scope="row"><%= job.notes %></td>
        <td scope="row">
          <span class="badge badge-<%= job.status_color %> w-100">
            <%= job.status_title %>
          </span>
        </td>
        <td scope="row"><%= link_to "Show", job %></td>
        <td scope="row"><%= link_to "Edit", edit_job_path(job) %></td>
        <td scope="row"><%= link_to_if !job.submitted?, "Stage", stage_job_path(job), method: :patch %></td>
        <td scope="row"><%= link_to_if job.staged?, "Files", job.files_url, target: "_blank" %></td>
        <td scope="row">
          <%=
            link_to(icon("fas", "play", "Submit"), submit_job_path(job),
              class: "btn btn-secondary btn-sm#{ " disabled" if !job.staged? || job.submitted?}",
              method: :patch
            )
          %>
        </td>
        <td scope="row">
          <%=
            link_to(icon("fas", "stop", "Stop"), stop_job_path(job),
              class: "btn btn-danger btn-sm#{ " disabled" unless job.submitted?}",
              method: :patch,
              data: { confirm: 'Are you sure?' }
            )
          %>
        </td>
        <td scope="row">
          <%=
            link_to(icon("fas", "trash", "Delete"), job,
              class: "btn btn-danger btn-sm",
              method: :delete,
              data: { confirm: 'Are you sure?' }
            )
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<h1 class="display-4 pb-2 my-2 border-bottom">
  New Batch Job
</h1>

<%= render 'form' %>

app/views/jobs/show.html.erb
<h1 class="display-4 pb-2 my-2 border-bottom">
  My Batch Job
</h1>

<p>
  <strong>Project:</strong>
  <%= @job.project %>
</p>

<p>
  <strong>Param1:</strong>
  <%= @job.param1 %>
</p>

<p>
  <strong>Param2:</strong>
  <%= @job.param2 %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @job.notes %>
</p>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <%= link_to Configuration.portal_title, "/", class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to icon("far", "list-alt", "My Batch Jobs"), jobs_path, class: "nav-link" %>
      </li>
      <li class="nav-item navbar-text">
        |
      </li>
      <li class="nav-item">
        <%= link_to icon("far", "plus-square", "New Batch Job"), new_job_path, class: "nav-link" %>
      </li>
      <li class="nav-item navbar-text">
        |
      </li>
      <li class="nav-item">
        <%= link_to icon("far", "clock", "My Active Jobs"), "/pun/sys/activejobs?jobcluster=owens&jobfilter=user", class: "nav-link", target: "_blank" %>
      </li>
    </ul>
    <span class="navbar-text">
      Logged in as <%= Configuration.current_user %>
    </span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Batch Job App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="turbolinks-root" content="<%= ENV["RAILS_RELATIVE_URL_ROOT"] %>">
  <%= csrf_meta_tags %>
</head>

<body>
  <header>
    <%= render partial: "layouts/nav" %>
  </header>
  <div class="container" role="main">
    <div class="mt-1">
      <%= render partial: "layouts/flash", flash: flash %>
    </div>
    <%= yield %>
  </div><!-- /.container -->
</body>

</html>